#!/bin/bash
echo "Publishing to gh-pages"
set -e
echo "-Change to branch gh-pages"
git fetch
git pull
git status
git checkout gh-pages
git merge --squash main

echo "-Build"
set +e
mkdir docs
rm -Rv docs/*
mv -Rv dist/apps/yacg-ng/browser/*
set -e
nx run yacg-ng:build:gh-pages

echo "-Move to Docs"
mv -v  dist/apps/yacg-ng/browser/*  docs/

echo "-Commit to GitHub"
git add docs
git commit -m "Published"
git push

echo "-Back to main branch"
git checkout -- *
git checkout main
git pull
git status
