#!/bin/bash
echo "Publishing to gh-pages"
set -e
echo "-Change to branch gh-pages"
git fetch
git pull
git status
git checkout gh-pages
#git merge --squash main
git merge --strategy-option=theirs -m "Publish"  main


echo "-Build"
set +e
rm -rf docs
rm -rf dist
set -e
nx run yacg-ng:build:gh-pages

echo "-Move to Docs"
mkdir docs
mv dist/apps/yacg-ng/browser/*  docs/

echo "-Commit to GitHub"
set +e
git add docs
git commit -m "Published"
git push
set -e

echo "-Back to main branch"
git checkout main
git pull
git status
